### ISSUE TITLE
Support for Namespaces

### ISSUE THREAD

**Issue by johntimothybailey** [namics/stylelint-bem-namics#10]
Enhancement to allow `namespace` to support a regular expression or array. 

**Context** I am working with a project right now on a project that has too namespaces (i.e. `mason` and `demo`)

I would like to do be able to do something like 

`"namespace": "mason-|demo-"`
OR
`"namespace": ["mason-", "demo-"]`

I am happy to submit a Pull Request if this idea is desired

**Comment by Regaddi** [comment]
What do you think @ernscht?
This might be a valid addition for projects using lerna, where the stylelint config is shared.

**Comment by ernscht** [comment]
The idea is good.
But i'm unsure what the best way for the configuration would be.

Currently we only use "namespace" as a string and arrays for prefixes ("patternPrefixes", "helperPrefixes").
But the idea with a regex is also valid.

To stay backwards compatible we could add the property "namespaces" for array values (with higher priority than "namespace" and start deprecating "namespace".

I would go for this:
```
"namespaces": ["...", "..."]
```

Other Opinions?

**Comment by jantimon** [comment]
I totally agree - allowing to use only one namespace can to limiting.

We should avoid adding to many different configuration and usages so maybe we could release a breaking chance which renames namespace to namespace and allow a string or an array of strings

Regular expressions will allow more flexibility but I can’t come up with a real useful scenario with so many namespaces that a regexp would be needed.

**Comment by jantimon** [comment]
@johntimothybailey it took me some time but I got a first draft - could you please take a look at #11 ?

**Comment by ernscht** [comment]
This is published as 5.1.0
