### ISSUE TITLE
allow scss variables in selectors

### ISSUE THREAD

**Issue by janwidmer** [namics/stylelint-bem-namics#13]
## Type of issue

* Feature request

With the current stylelint-bem, it's not possible to use an scss variable within a selector. This feature which exists for SCSS is quite handy to use within mixins to realize something like this:

```
@mixin some-mixin($selector) {
	/* stylelint-disable plugin/stylelint-bem-namics */
	#{$selector} {
            // your styles
        }
        /* stylelint-enable plugin/stylelint-bem-namics */
}
```

Could we consider to add this feature?

**Comment by jantimon** [comment]
Unfortunately it is not possible to lint scss variables.

Variable selectors will probably only be used inside utils as they are very hard to maintain.
