### ISSUE TITLE
Is there any way to close the config of 'contain no uppercase letters'

### ISSUE THREAD

**Issue by nicholaslee119** [namics/stylelint-bem-namics#6]
According to the BEM [naming convention](https://en.bem.info/methodology/naming-convention/),
There are many styles of naming convention, not just 'contain no uppercase letters'
I am wondering are there some way to close the config of 'contain no uppercase letters'?

**Comment by nicholaslee119** [comment]
anyway, I PR for this 😄

**Comment by ernscht** [comment]
Thanks a lot for your input.
Because of simplicity, readability and consistency we decided to go the way allowing only small letters in our rules. But, this is not yet set in stone - the idea sounds interesting.
We will reconsider our decision, check your PR and try to merge with our ideas for naming - but we need some time ;-)

**Comment by jantimon** [comment]
@nicholaslee119 your pull request looks really nice but unfortunately I am with ernscht.  
Small cased class names are a standard which is very widely used over the web.

According to [stackoverflow](https://stackoverflow.com/a/2345300/159319):

"Using uppercase, dashes or underscores when naming css selectors"

> The CSS spec does not specify how browsers should handle case, so using camelCase leaves one open to ambiguous interpretation.

**Comment by barrynorman** [comment]
Thats really sad :(
We are using the CamelCase style and this would be a really nice feature. Since @nicholaslee119 did already the work, why did you not merge it?

**Comment by enterframe** [comment]
me too, ernscht.
Im also interested in using this with PascalCase

**Comment by ernscht** [comment]
Sorry, guys.

Besides @jantimon 's argument (see above), there was another reason not to take over the PR: It was not ready. For example, the linter would not work with PascalCase names, which you want to use.

So, we decided to not apply a PR with a config param which allows classes like `m-applEBlock` or `o-bAnAnAbLOCK` and, at the same time, disallows classes like `m-AppleBlock`.

You see, it's not easy, and we actually want to stick with a small, simple linter.

**Comment by barrynorman** [comment]
Ok, so I why not add options for the different BEM styles? I agree that we don't want to habe something like `bAnAnAbLOCK` or `m-applEBlock` either ;)

See "Alternative naming schemes" from https://en.bem.info/methodology/naming-convention/
