### ISSUE TITLE
Split code formatting from naming convention

### ISSUE THREAD

**Issue by Regaddi** [namics/stylelint-bem-namics#8]
Hey,

it'd be super practical, if we'd split the code formatting config from the BEM naming config.
We don't use this package right now in e.g. React projects, where we use component based style loading and therefore don't need BEM.
However it would be great, if we included a default code formatting configuration, that provides default configurations for our CSS files.
I'd suggest to split this package into two separate ones: one for BEM and the other for basic CSS code formatting.

**Comment by ernscht** [comment]
Hey Chris
This is just a stylelint plugin for the bem-linting part. it's an addition to other css linting rules which are defined elsewhere. (e.g https://github.com/namics/frontend-defaults/blob/master/codequality/stylelint/.stylelintrc)

I do not understand where you could split here.

**Comment by Regaddi** [comment]
I totally missed out, that the general linting configuration is at frontend-defaults.
Everything's good 😄
