### ISSUE TITLE
Option disallow nested elements

### ISSUE THREAD

**Issue by gitnik** [namics/stylelint-bem-namics#9]
BEM does not allow for nested elements, which this plugin does currently not complain about. It would be great to have this either changed or at least be configureable

**Comment by jantimon** [comment]
Could you please add an example?

**Comment by ernscht** [comment]
I suspect @gitnik speaks of nested elements like this: `block__element__subelement` (we allow that)

@gitnik, Where did you get the statement: 
> "BEM does not allow for nested elements" ?

There are many different BEM-style conventions around. Maybe somewhere nested elements are not recommended (but not forbidden).
I agree with you, such a configuration option would be great.
We keep the idea and are open for a PR.

If you want to have much more flexibility, maybe [stylelint-selector-bem-pattern](https://github.com/simonsmith/stylelint-selector-bem-pattern) could help.

**Comment by jantimon** [comment]
When we tried to create modules we were often faced situations where elements required a sub element.

You could still use this plugin and add a more strict rule to your stylelint which forbids subelements.
